server:
    port: 8060

spring:
    application:
        name: gem-config
    cloud:
      config:
        server:
          git:
            uri: https://github.com/forezp/SpringcloudConfig/
            searchPaths: respo
            username: aa
            password: aa
        label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://center1:8071/eureka/,http://center2:8072/eureka/,http://center3:8073/eureka/
      