spring:
    application:
        name: gem-gate
    profiles:
      active: g1
        
zuul:
  ignored-services: microservice-provider-user # 需要忽视的服务(配置后将不会被路由)
  routes:
    api-a:
      path: /api/a/**
      serviceId: gem-monitor
    api-b:
      path: /api/b/**
      serviceId: gem-monitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://center1:8071/eureka/,http://center2:8072/eureka/,http://center3:8073/eureka/
      